### ISSUE TITLE
Not receiving discord token and passwords

### ISSUE THREAD

**Issue by lexxxxxxx7** [Rdimo/Hazard-Token-Grabber-V2#282]
The webhook works and I receive both a roblox token and a screenshot. But I don't get their discord token(though they have an account) or passwords. Is it possible that an extension could block the script from receiving those two things but still allow the rest of the information to send. For example could adguard block this process from happening or is there another reason as to why I am not receiving all the information I should be?

**Comment by Rdimo** [comment]
are you talking about the injection or hazard itself

**Comment by lexxxxxxx7** [comment]
Mainly the injection because it looks as though Hazard Works apart from that.

**Comment by Rdimo** [comment]
> Mainly the injection because it looks as though Hazard Works apart from that.

ye the I updated the injection 10h ago so it should work now, discord updated some stuff which messed up with the injection and such so pretty much the only token grabber and discord injection thats working right now is hazard v2 and my discord-injection

**Comment by lexxxxxxx7** [comment]
![image](https://user-images.githubusercontent.com/103804488/168510390-9c224e50-8062-426e-ab14-2d1fa0e736c8.png)
Still not getting any tokens after the injection update, did I need to redownload hazard?

**Comment by lexxxxxxx7** [comment]
Saw the new update I'll install the new update and retry

**Comment by lexxxxxxx7** [comment]
Still doesn’t work

**Comment by novauwu** [comment]
cant even find the file 💀

**Comment by nizehacking** [comment]
My webhook doesn't work either

**Comment by Rdimo** [comment]
> ![image](https://user-images.githubusercontent.com/103804488/168510390-9c224e50-8062-426e-ab14-2d1fa0e736c8.png) Still not getting any tokens after the injection update, did I need to redownload hazard?

think ur getting it wrong, the injection and hazard v2 are seperate, they are not merged in some sort of way. If the injection is broken hazard v2 would still work, same it if were the other way around.

**Comment by Rdimo** [comment]
one more thing @lexxxxxxx7 if it says "No tokens extracted" then it most likely means that the victim simply just doesnt have discord or atleast a supported platform that can be grabbed from
